'use client';

import { useRef, useState } from 'react';
import { useGlide } from '@/components/chrome/useGlide';

export interface FeaturedItem {
  href: string;
  title: string;
  model: string;
}

/**
 * Live-Vorschau ausgewählter Läufe (run.json → "featured"). Die Artefakte sind
 * fremder, generierter Code: iframe ohne allow-same-origin, zusätzlich liefert
 * Caddy /sites/* mit CSP-Sandbox aus (deploy/Caddyfile).
 */
export function FeaturedPreview({ items }: { items: FeaturedItem[] }) {
  const [active, setActive] = useState(0);
  const [loaded, setLoaded] = useState<Record<string, true>>({});
  // Erst gezeigte Vorschauen werden gemountet; einmal geladen bleiben sie erhalten.
  const [seen, setSeen] = useState<Record<number, true>>({ 0: true });
  const tabs = useRef<(HTMLButtonElement | null)[]>([]);
  const current = items[active];
  const [tabsRef, glideRef] = useGlide<HTMLDivElement, HTMLSpanElement>('[role="tab"]', active);

  const select = (i: number) => {
    setActive(i);
    setSeen((s) => ({ ...s, [i]: true }));
    tabs.current[i]?.focus();
  };

  const onKey = (e: React.KeyboardEvent, i: number) => {
    const next = e.key === 'ArrowRight' ? (i + 1) % items.length : e.key === 'ArrowLeft' ? (i - 1 + items.length) % items.length : e.key === 'Home' ? 0 : e.key === 'End' ? items.length - 1 : null;
    if (next === null) return;
    e.preventDefault();
    select(next);
  };

  return (
    <div className="pf-preview-box">
      <div role="tablist" aria-label="Featured runs" className="pf-preview-box__tabs" ref={tabsRef}>
        {/* Helle Markierung gleitet zum gewählten Tab (useGlide). */}
        <span className="pf-glide pf-glide--bright" ref={glideRef} aria-hidden="true" />
        {items.map((item, i) => (
          <button
            key={item.href}
            ref={(el) => { tabs.current[i] = el; }}
            role="tab"
            id={`tab-${i}`}
            aria-selected={active === i}
            aria-controls={`panel-${i}`}
            tabIndex={active === i ? 0 : -1}
            onClick={() => select(i)}
            onKeyDown={(e) => onKey(e, i)}
          >
            {item.title}
          </button>
        ))}
      </div>
      <div className="pf-preview-box__frame pf-card">
        <div className="pf-preview-box__bar">
          <span className="pf-preview-box__url">neuralhub.dev{current.href}</span>
          <a href={current.href} target="_blank" rel="noopener noreferrer">Open ↗</a>
        </div>
        <div className="pf-preview-box__stage">
          {items.map((item, i) => (
            <div key={item.href} id={`panel-${i}`} role="tabpanel" aria-labelledby={`tab-${i}`} hidden={active !== i}>
              {seen[i] && (
                <iframe
                  src={item.href}
                  title={`${item.title}, generated by ${item.model}`}
                  sandbox="allow-scripts"
                  loading="lazy"
                  onLoad={() => setLoaded((l) => ({ ...l, [item.href]: true }))}
                  className={loaded[item.href] ? 'is-loaded' : ''}
                />
              )}
              {!loaded[item.href] && <span className="pf-preview-box__loading">Loading preview …</span>}
            </div>
          ))}
        </div>
      </div>
      <p className="pf-preview-box__caption">Generated by <b>{current.model}</b>, served exactly as it came out.</p>
    </div>
  );
}
